version: "3.7"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=matcha
    ports:
      - 5427:5432
    volumes:
      - db:/pgdata
  # app:
  #   depends_on:
  #     - postgres
  #   build: ./server
  #   env_file: ./.env
  #   ports:
  #     - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
  #   environment:
  #     - DB_HOST=postgres
  #     - DB_USER=$POSTGRES_USER
  #     - DB_PASSWORD=$POSTGRES_PASSWORD
  #     - DB_NAME=$POSTGRES_DATABASE
  #     - DB_PORT=$POSTGRES_DOCKER_PORT
volumes:
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/matcha_data